<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <style>
   .gordo{
    width: 900px;
    
   }

  </style>
</head>
<body>

<img src="./png-transparent-coffee-know-your-meme-cafe-drink-food-coffee-television-white-food.png" alt="">
  <img  class="gordo" src="./pngwing.com.png" alt="">
</body>
</html>